import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ScrollToTop from "../src/components/ui/ScrollToTop";
import Header from "@/src/components/Header";
import Footer from "@/src/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Header toujours en haut */}
        <Header />

        {/* Contenu principal */}
        <main className="flex-grow">{children}</main>

        {/* Footer toujours en bas */}
        <Footer />

        {/* Bouton pour remonter */}
        <ScrollToTop />
      </body>
    </html>
  );
}
